### ISSUE TITLE
Missing json files?

### ISSUE THREAD

**Issue by jchannon** [sixeyed/widgetario#1]
Hi, just browsing and found a reference to missing files?
https://github.com/sixeyed/widgetario/blob/main/src/web/dotnet/Widgetario.Web/Program.cs#L31

What would be in these files?

Thanks

**Comment by sixeyed** [comment]
Those are optional config files; you can specify settings in there to override the defaults in appsettings.json. The app runs fine without them in Docker Compose, but you can load different settings with a file mount if you need to (e.g. to load ConfigMaps and Secrets from Kubernetes).
